sudo: required
services:
  - docker

before_install:
  - docker build -t babagadji/docker_first_step -f Dockerfile.dev .

script: 
  - docker run babagadji/docker_first_step npm run test  -- -- coverage

  